#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

${DOCROOT}/plugins/active.directory/scripts/rc.startup > /dev/null 2>&1
${DOCROOT}/plugins/active.directory/scripts/rc.active.directory apply > /dev/null 2>&1
